//
// Created by cantte on 27/04/21.
//

#ifndef NEURONAL_NETWORKS_SERVER_ALLMODELS_H
#define NEURONAL_NETWORKS_SERVER_ALLMODELS_H

#include "Madeline.h"

#endif //NEURONAL_NETWORKS_SERVER_ALLMODELS_H
